# Generated by Django 4.2.4 on 2023-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='image/')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
